config/routes.rb
Rails.application.routes.draw do
  get "rents/index"
  get "rents/confirmation"
  get "rents/show"
  devise_for :users
  resources :products
  resources :rents, only: [:create, :confirmation, :index, :show, :destroy] do
    collection do
      post :confirmation
    end
  end
  get "homes/top"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "homes#top"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :rents

  def rents_new
    rents.new
  end
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :product
  belongs_to :user

  def save_rent(rent, rent_params)
    rent.start_date = rent_params[:start_date]
    rent.end_date = rent_params[:end_date]
    rent.user_id = rent_params[:user_id]
    rent.product_id = rent_params[:product_id]
    save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
  has_many :rents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.image.attached?
      @product.image.attach(params[:product][:image])
    else
      @product.image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'default.png')), 
                        filename: 'default.png', 
                        content_type: 'image/png')
    end

    if @product.save
      flash[:success] = "productを新規登録しました"
      redirect_to :products
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @product = Product.find(params[:id])
    @rents = @product.rents
    @rent = @rents.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:success] = "PRODUCT IDが「#{@product.id}」の情報を更新しました"
      redirect_to :products
    else
      render "edit"
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:success] = "productを削除しました"
    redirect_to :products
  end

  private
  def product_params
    params.require(:product).permit(:name, :image, :user_id).merge(user_id: current_user.id)
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  def index
    @rents = Rent.all
  end

  def create
    @rent = Rent.new(rent_params)

    if @rent.save
      redirect_to @rent, success: '予約が完了しました。'
    else
      @product = @rent.product
      render :confirmation, status: :unprocessable_entity
    end
  end

  def confirmation
    @product = Product.find(params[:rent][:product_id])
    @rent = @product.rents.new(rent_params)
  end

  def show
    @rent = Rent.find(params[:id])
  end

  private
  def rent_params
    params.require(:rent).permit(:start_date, :end_date, :product_id, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>
<p><%= link_to "product一覧", :products %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Myapp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "turbo", type: "module" %>
  </head>

  <body>
    <h1>デフォルト画像機能</h1>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <br>
    <%= link_to "ログイン", :new_user_session %>
    <%= link_to "新規登録", :new_user_registration %>
    <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "ログアウトしますか？" } %>
    <%= link_to "HOME", :root %>
    <%= link_to "レンタル一覧", rents_index_path %>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>
<h1>product編集</h1>
<%= form_with model: @product do |f| %>
<table>
  <tr>
    <th><%= f.label :name, "名前" %></th>
    <td><%= f.text_field :name %></td>
  </tr>
  <tr>
    <th><%= f.label :image, "画像" %></th>
    <td><%= f.file_field :image %></td>
  </tr>
</table>
<div>
  <ul>
    <li><%= f.submit "編集を完了する" %></li>
    <li><%= link_to "product一覧に戻る", :products %></li>
  </ul>
</div>
<% end %>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>
<h1>product一覧</h1>
<% if flash[:success] %>
  <p class="success"><%= flash[:success] %></p>
<% end %>

<% @products.each do |product| %>
  <p>--------------------------------------------------------------------</p>
  <p>product_id: <%= product.id %></p>
  <p>product名: <%= product.name %></p>
  <p>
    画像:
    <% if product.image.attached? %>
      <%= image_tag product.image, size: '50x50' %>
    <% else %>
      <%= image_tag asset_path('default.png'), size: '50x50' %>
    <% end %>
  </p>
  <p><%= link_to "情報", product %></p>
  <p><%= link_to "編集", [:edit, product] %></p>
  <p><%= link_to 'product削除', product, data: { turbo_method: :delete, turbo_confirm: "productを削除しますか？" } %></p>
  <p><%= product.updated_at %></p>
  <p><%= product.created_at %></p>
<% end %>
<p><%= link_to "product新規登録", :new_product %></p>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>
<p>product新規作成</p>
<%= form_with model: @product do |f| %>
<table>
  <tr>
    <th><%= f.label :name, "名前" %></th>
    <td><%= f.text_field :name %></td>
  </tr>

  <tr>
    <th><%= f.label :image, "画像" %></th>
    <td><%= f.file_field :image %></td>
  </tr>
</table>
<div>
  <ul>
    <li><%= f.submit "登録完了する"%></li>
    <li><%= link_to "product一覧に戻る", :products %></li>
  </ul>
</div>
<% end %>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>
<h1>product詳細</h1>
<table>
  <tr>
    <th>名前</th>
    <td><%= @product.name %></td>
  </tr>

  <tr>
    <th>画像</th>
    <td>
      <% if @product.image.attached? %>
        <%= image_tag @product.image, size: '50x50' %>
      <% else %>
        <%= image_tag asset_path('default.png'), size: '50x50' %>
      <% end %>
    </td>
  </tr>
</table>
<div>
  <ul>
    <li><%= link_to "product一覧に戻る", :products %></li>
  </ul>
</div>

<% if user_signed_in? %>
  <%= form_with model: @product do |f| %>
    <%= f.hidden_field :id, value: @product.id %>
    <%= f.hidden_field :name, value: @product.name %>
    <%= f.hidden_field :image, value: @product.image %>
  <% end %>
<% end %>

<% @rents.each do |rent| %>
  <p class="h3"><%= rent.start_date %></p>
  <p class="h3"><%= rent.end_date %></p>
  <label><%= rent.created_at %></label>
<% end %>

<% if user_signed_in? %>
  <%= form_with model: @rent, url: confirmation_rents_path, method: :post, local: true, data: { turbo: false } do |f| %>
    <ul>
      <%= f.hidden_field :product_id, value: @product.id %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <li>開始日<%= f.date_field :start_date %></li>
      <li>終了日<%= f.date_field :end_date %></li>
      <li><%= f.submit "確認画面へ" %></li>
    </ul>
  <% end %>
<% end %>

app/views/rents/confirmation.html.erb
<h1>確認画面</h1>
<p>名前: <%= @product.name %></p>
<p>開始日: <%= @rent.start_date.to_formatted_s(:datetime_jp) %></p>
<p>終了日: <%= @rent.end_date.to_formatted_s(:datetime_jp) %></p>

<%= form_with url: rents_path, method: :post, local: true, data: { turbo: false } do |f| %>
  <%= f.hidden_field :product_id, value: @product.id, name: 'rent[product_id]' %>
  <%= f.hidden_field :user_id, value: current_user.id, name: 'rent[user_id]' %>
  <%= f.hidden_field :start_date, value: @rent.start_date, name: 'rent[start_date]' %>
  <%= f.hidden_field :end_date, value: @rent.end_date, name: 'rent[end_date]' %>
  <%= f.submit "予約を確定する" %>
<% end %>
<p><%= link_to "キャンセル", :products %></p>

app/views/rents/create.html.erb
<h1>Rents#create</h1>
<p>Find me in app/views/rents/create.html.erb</p>

app/views/rents/index.html.erb
<h1>予約一覧</h1>
<% @rents.each do |rent| %>
  <table class="show-table">
    <tr>
      <th>名前</th>
      <td><%= rent.product.name %></td>
    </tr>

    <tr>
      <th>画像</th>
      <td>
        <% if rent.product.image.attached? %>
          <%= image_tag rent.product.image, size: '50x50' %>
        <% else %>
          <%= image_tag rent.asset_path('default.png'), size: '50x50' %>
        <% end %>
      </td>
    </tr>

    <tr>
      <th>開始日</th>
      <td><%= rent.start_date.to_formatted_s(:datetime_jp) %></td>
    </tr>
    <tr>
      <th>終了日</th>
      <td><%= rent.end_date.to_formatted_s(:datetime_jp) %></td>
    </tr>
    <tr>
      <th>予約した日にち</th>
      <td><%= rent.created_at.to_formatted_s(:datetime_jp) %></td>
    </tr>
    <p>--------------------------------------------------</p>
  </table>
<% end %>

app/views/rents/show.html.erb
<h1>予約内容</h1>
<table class="show-table">
<tr>
  <th>名前</th>
  <td><%= @rent.product.name %></td>
</tr>

<tr>
  <th>画像</th>
  <td>
    <% if @rent.product.image.attached? %>
      <%= image_tag @rent.product.image, size: '50x50' %>
    <% else %>
      <%= image_tag @rent.asset_path('default.png'), size: '50x50' %>
    <% end %>
  </td>
</tr>

<tr>
  <th>開始日</th>
  <td><%= @rent.start_date %></td>
</tr>

<tr>
  <th>終了日</th>
  <td><%= @rent.end_date %></td>
</tr>

<tr>
  <th>予約した日にち</th>
  <td><%= @rent.created_at %></td>
</tr>
<p>--------------------------------------------------</p>
</table>